import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <ClerkProvider 
      appearance={{
        variables: {
          colorPrimary: "#0070f3",
          colorText: "#fff",
          colorBackground: "black",
          colorInputBackground: "#ffffff",
          colorInputBorder: "white",
          colorInputPlaceholder: "#ffffff",
        },
        elements: {
          socialButtonsBlockButton:{
            backgroundColor: "#fff",
            color: "black",
            border: "1px solid #333333",
            "&:hover": {
              backgroundColor: "#f0f0f0",
            },
          },
        },  
      }}
    >
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-800 flex-wrap`}
      >
      <Providers >
        <Navbar />
        <div className="flex">
          {children}
        </div>
      </Providers>
      </body>
      
    </html>
    </ClerkProvider>
  );
}
